name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run NickNamer
        run: |
          sudo systemctl restart namer.service
